Makefile modularization
ShilaTu/esp32-core pull request #11
Opened 2019-12-07 13:00 UTC by nopeslide

2019-12-08 11:49 UTC, ikstream requested changes
What's the advantage of moving staff to a hidden file instead of keeping it in just one?

2019-12-08 11:49 UTC, ikstream commented on Makefile
No comments, keep it in or remove it

2019-12-08 11:49 UTC, ikstream commented on Makefile
No comments, keep it in or remove it

2019-12-08 11:49 UTC, ikstream commented on Makefile
> +
No comments, keep it in or remove it

2019-12-08 13:51 UTC, nopeslide commented
> What's the advantage of moving staff to a hidden file instead of keeping it in just one?

The same logic exists in `/Makefile` & `/docker/Makefile`, the next step would be to simplify the docker Makefile. I dot-prefixed it so it doesn't clutter the root.

2019-12-09 07:43 UTC, ikstream requested changes
Please add some instructions on how to use the updated Makefile

2019-12-09 12:14 UTC, ikstream approved these changes

2019-12-09 12:14 UTC, merged