firmware: feature added espidf-ulp-adc example as minimal build
ShilaTu/esp32-core pull request #13
Opened 2019-12-07 15:46 UTC by jhonnyam

copied the example code and adapted it

2019-12-07 19:51 UTC, nopeslide requested changes

2019-12-07 19:51 UTC, nopeslide commented on platformio.ini
>  [env:nodemcu]
should be `debug` or `release`

2019-12-07 19:51 UTC, nopeslide commented on platformio.ini
>  board = nodemcu-32s
move this into globale env and set it to the actual board

2019-12-07 19:51 UTC, nopeslide commented on platformio.ini
> +build_flags = -DCONFIG_WIFI_SSID=\"ESP_AP\" -DCONFIG_WIFI_PASSWORD=\"MYPASS\"
```suggestion
build_flags =
  -DCONFIG_WIFI_SSID=\"ESP_AP\"
  -DCONFIG_WIFI_PASSWORD=\"MYPASS\"
```
it's more readable this way. but please check if an empty first line is permitted

2019-12-07 19:51 UTC, nopeslide commented on src/ulp_adc_example_main.c
> +}
put `app_main` in an extra file int the src root dir

2019-12-13 21:59 UTC, nopeslide requested changes

2019-12-13 21:59 UTC, nopeslide commented on platformio.ini
> +>>>>>>> 37d26654a794bd18313ccf1e255576bc9ace1ac2
looks like a merge conflict

2019-12-19 14:46 UTC, ikstream requested changes
Could you please update the comments, so they match them used in ShilaTu/esp32-core#28

2020-02-12 10:15 UTC, closed without merging

2020-02-12 10:21 UTC, jhonnyam commented
This changes where made useless by #32