github:feature added issue/pr templates
ShilaTu/esp32-core pull request #48
Opened 2020-03-18 21:53 UTC by nopeslide

I would like to have various templates to speed up issue/pr filing.
open to suggestions, feel free to commit into this branch.

2020-03-19 12:56 UTC, ikstream reviewed
I am not sure what's the difference between clean workspace/build/container

`make clean; make all` would fit all, wouldn't it?

Assignees is something you would need to set and edit the issue. An assignment can be done through GH internal and don't need 2 be in the issue head, don't you think?

Otherwise LGTM

2020-03-19 13:05 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/bug.md
> +- [ ] clean container
```suggestion
- [ ] git pull
- [ ] make clean
- [ ] make dirclean
- [ ] make distclean
```

2020-03-19 13:06 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/bug.md
> +- [ ] clean container
> Assignees is something you would need to set and edit the issue. An assignment can be done through GH internal and don't need 2 be in the issue head, don't you think?

didn't touch this, it was autogenerated by github

2020-03-19 14:41 UTC, ikstream approved these changes

2020-03-19 16:15 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/bugfix.md
> +- [ ] clean container
```suggestion
- [ ] make clean
- [ ] everything staged
- [ ] compiles without warnings
- [ ] test added
- [ ] tested
```

2020-03-19 16:16 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/feature.md
> +- [ ] clean container
- [ ] make clean
- [ ] everything staged
- [ ] compiles without warnings
- [ ] test added
- [ ] tested

2020-03-20 07:10 UTC, ikstream requested changes
I would remove `tested` and `compiles without warnings` this is something we should expect from every pull request. If it doesn't it should be explicitly stated in the pull request with reasoning why. We should build everything by our self in addition to the CI test before merging it into upstream to be safe anyway.

2020-03-20 08:27 UTC, nopeslide commented
> I would remove `tested` and `compiles without warnings` this is something we should expect from every pull request. If it doesn't it should be explicitly stated in the pull request with reasoning why. We should build everything by our self in addition to the CI test before merging it into upstream to be safe anyway.

What about PR Drafts and on device testing?
A PR should conform to all of these items, so they are more of reminders.
If your code does not compile: we have an unchecked box that forces a explanation.

2020-03-22 18:35 UTC, ikstream commented
> What about PR Drafts and on device testing?
> A PR should conform to all of these items, they act as reminders.
> If your code does not compile: we have an unchecked box that forces an explanation.
Don't we have compile tests? If they fail there is some explanation anyways?

2020-03-23 12:44 UTC, nopeslide reviewed
Simplified everything a little bit

2020-03-23 12:44 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/feature.md
> +**Is your feature request related to a problem? Please describe.**
```suggestion
**Description**
```

2020-03-23 12:44 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/feature.md
> +A clear and concise description of any alternative solutions or features you've considered.
```suggestion
**Alternative solution**
A clear and concise description of any alternative solutions or features you've considered.
- first alternative solution
- second alternative solution
```

2020-03-23 12:44 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/feature.md
> +A clear and concise description of what you want to happen.
```suggestion
**Solution**
A clear and concise description of your preferred solution.
```

2020-03-23 12:44 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/bug.md
> +Add any other context about the problem here.
```suggestion
**Context**
If applicable, add screenshots or code to help explain your problem and any other context about the problem here.
```

2020-03-23 12:44 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/feature.md
> +Add any other context or screenshots about the feature request here.
```suggestion
**Context**
If applicable, add screenshots or code to help explain your problem and any other context about the problem here.
```

2020-03-23 12:44 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/bugfix.md
> +Name the the issues, this bugfix solves.
```suggestion
**Related Issues & PRs**
Name the issues & PRs, this bugfix solves or relates to.
If no issue exists, create one!
- #??
- #??
```

2020-03-23 12:44 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/bugfix.md
> +- [ ] no related PR
```suggestion
- [ ] tests added
- [ ] documentation added
```

2020-03-23 12:44 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/feature.md
> +Name related PR and issues.
```suggestion
**Related Issues & PRs**
Name related PR and issues.
If no issue exists, create one!
- #??
- #??
```

2020-03-23 12:44 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/feature.md
> +- [ ] no related PR
```suggestion
- [ ] tests added
- [ ] documentation added 
```

2020-03-23 12:44 UTC, nopeslide commented on .github/PULL_REQUEST_TEMPLATE/feature.md
> +
```suggestion

**Context**
If applicable, add screenshots or code to help explain your problem and any other context about the problem here.

```

2020-03-23 12:44 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/bug.md
> +- [ ] no related issue
```suggestion
```

2020-03-23 13:13 UTC, nopeslide commented on .github/ISSUE_TEMPLATE/bug.md
> +- [ ] no related issue
either the bug is reproducable or not.
A check on related issues has no meaning at all

2020-03-24 16:35 UTC, ikstream submitted a review, later dismissed

2020-03-24 16:41 UTC, ikstream approved these changes
lgtm

2020-03-24 16:42 UTC, merged