docker:feature added idf image/container generation
ShilaTu/esp32-core pull request #50
Opened 2020-03-22 19:08 UTC by nopeslide

regarding #48

- [ ] add idf docker image
- [ ] add idf docker container
- [ ] rebase other docker images on idf
- [ ] restructure repo
- [ ] rebase main Makefile to use idf docker

2020-03-26 17:38 UTC, nopeslide reviewed
seems reviewable.
a little bit more documentation needs to be added

2020-03-28 18:52 UTC, jhonnyam reviewed
Looks good

2020-03-28 18:52 UTC, jhonnyam commented on Makefile
> +		idf.py \
Should be just `idf`

2020-03-28 18:52 UTC, jhonnyam commented on Makefile
>  		pio \
should be `idf`

2020-03-29 11:40 UTC, jhonnyam requested changes
Looks good

2020-03-29 11:40 UTC, jhonnyam commented on components/template/CMakeLists.txt
> +	INCLUDE_DIRS
Bad alignemnt

2020-03-29 12:40 UTC, jhonnyam approved these changes

2020-03-29 12:41 UTC, merged