idf:refactor moved projects into own subdir
ShilaTu/esp32-core pull request #55
Opened 2020-03-31 11:25 UTC by nopeslide

## Related Issues & PRs

none

## Description

- [x] moved main project into lifesensor
- [x] renamed test project into lifesensor_test
- [x] introduced Makefile variable PROJECT which chooses project
- [x] made clean target work without dockeror idf
- [x] made build target run idf reconfigure
- [x] updated README.md
- [x] refactored .gitignores

## Context

I moved the project into subdirs to allow for project flavors like unit_testing or coming simulation specific stuff.

## Testing

- [x] tested building
- [x] tested flashing
- [x] tested monitoring 

## Documentation

- [x] documented new Makefile variable

2020-03-31 11:51 UTC, nopeslide commented on README.md
> +## Projects flavors
```suggestion
## Project flavors
```

2020-03-31 11:51 UTC, nopeslide commented on README.md
> +  1. Choosing main project
```suggestion
  1. Choosing project flavor
```

2020-03-31 11:53 UTC, nopeslide reviewed
fixed some typos

2020-03-31 12:04 UTC, nopeslide reviewed
think I got everything now

2020-04-03 11:27 UTC, nopeslide commented
cleaned up PR

2020-04-03 13:53 UTC, ikstream requested changes
lgtm, but would be good to test it very extensively first, as with #56 
@pascalharp @jhonnyam @reporiot

2020-04-05 22:11 UTC, reporiot reviewed
lgtm

2020-04-07 06:43 UTC, ikstream approved these changes

2020-04-07 06:43 UTC, merged